---
- name: Configure | nginx | ulimit
  lineinfile:
    state: present
    dest: /etc/default/nginx
    regexp: '#* *ULIMIT'
    line: "ULIMIT='-n {{ nginx_worker_connections }}'"
  notify: Reload Service | nginx
  tags:
    - configuration
    - precise-configuration
    - performance
    - nginx

- name: Upload Config | nginx
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | nginx
  tags:
    - configuration
    - template-configuration
    - nginx

- name: Disable Config | nginx | default
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: Reload Service | nginx
  tags:
    - configuration
    - disable-configuration
    - disable-default
    - nginx

- name: "Directory Exists | {{ nginx_docroot }}"
  file:
    state: directory
    path: "{{ nginx_docroot }}"
    owner: "{{ nginx_user }}"
    group: wcadmin
    mode: 0775
  when: nginx_using_standard_docroot
  tags:
    - directory-structure
    - nginx
