---
- name: Configure | nginx | ulimit
  lineinfile:
    state: present
    dest: /etc/default/nginx
    regexp: '#* *ULIMIT'
    line: "ULIMIT='-n {{ nginx_worker_connections }}'"
  notify: Reload Service | nginx
  tags:
    - configuration
    - precise-configuration
    - performance
    - nginx

- name: Upload Config | nginx
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | nginx
  tags:
    - configuration
    - template-configuration
    - nginx

- name: Disable Config | nginx | default
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: Reload Service | nginx
  tags:
    - configuration
    - disable-configuration
    - disable-default
    - nginx

- name: Upload Config | nginx | Standard
  template:
    src: "etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | nginx
  with_items:
    - no-ssl
    - require-ssl
    - static
    - php

- name: Enable Config | nginx | static
  file:
    state: link
    src: /etc/nginx/sites-available/static.conf
    dest: /etc/nginx/sites-enabled/static
  notify: Reload Service | nginx
  when: nginx_static_server

- name: Enable Config | nginx | php-application
  file:
    state: link
    src: /etc/nginx/sites-available/php-application.conf
    dest: /etc/nginx/sites-enabled/php-application
  notify: Reload Service | nginx
  when: nginx_php_application_server

- name: Enable Config | nginx | SSL Enforced
  file:
    state: link
    src: /etc/nginx/sites-available/require-ssl.conf
    dest: /etc/nginx/sites-enabled/require-ssl
  notify: Reload Service | nginx
  when: nginx_ssl_enforced

- name: Enable Config | nginx | SSL Disabled
  file:
    state: link
    src: /etc/nginx/sites-available/no-ssl.conf
    dest: /etc/nginx/sites-enabled/no-ssl
  notify: Reload Service | nginx
  when: nginx_ssl_disabled

- name: "Directory Exists | {{ nginx_docroot }}"
  file:
    state: directory
    path: "{{ nginx_docroot }}"
    owner: "{{ nginx_user }}"
    group: wcadmin
    mode: 0775
  when: nginx_using_standard_docroot
  tags:
    - directory-structure
    - nginx
