---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - nginx-naxsi

- name: Install Packages | pip
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - ngxtop

- name: Service Stopped | nginx
  service:
    name: nginx
    state: stopped
  tags:
    - disruptive

- name: Kill Process | nginx
  command: killall nginx
  ignore_errors: True
