---
- name: Include install from repository
  include: install-repo.yml
  when: not nginx_install_from_source

- name: Include install from source
  include: install-source.yml
  when: nginx_install_from_source
