---
- name: "Directory Exists | {{ nginx_log_root }}"
  file:
    state: directory
    path: "{{ nginx_log_root }}"
    owner: "{{ nginx_user }}"
    group: wcdevelop
    mode: 0775
  tags:
    - directory-structure
    - logging
    - nginx

- name: Upload Config | logrotate | nginx
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: wcadmin
    mode: 0664
  with_items:
    - etc/logrotate.d/nginx
  tags:
    - nginx
    - logrotate
