---
- name: "Directory Exists | {{ nginx_log_root }}"
  file:
    state: directory
    path: "{{ nginx_log_root }}"
    owner: "{{ nginx_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - nginx

- name: Upload Config | beaver | nginx
  template:
    src: etc/beaver/conf.d/nginx
    dest: /etc/beaver/conf.d/nginx
  tags:
    - configuration
    - template-configuration
    - logging
    - using-beaver
    - nginx
