---
- name: "Directory Exists | {{ nginx_log_root }}"
  file:
    state: directory
    path: "{{ nginx_log_root }}"
    owner: "{{ nginx_user }}"
    group: wcdevelop
    mode: 0775
  tags:
    - directory-structure
    - logging
    - nginx

- name: Update logrotate | nginx
  replace:
    dest: "{{ item }}"
    regexp: '/var/log/nginx'
    replace: "{{ nginx_log_root }}"
  with_items:
    - /etc/logrotate.d/nginx
  tags:
    - initscript
    - runtime-data
    - pidfile
    - nginx
