---
- name: "Directory Exists | {{ nginx_runtime_root }}"
  file:
    state: directory
    path: "{{ nginx_runtime_root }}"
    owner: "{{ nginx_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - nginx

- name: Configure Initscript | nginx
  replace:
    dest: /etc/init.d/nginx
    regexp: '/var/run/\$NAME.pid'
    replace: "{{ nginx_pidfile_path }}"
  tags:
    - initscript
    - runtime-data
    - pidfile
    - nginx

- name: Upload Config | monit | nginx
  template:
    src: etc/monit/conf.d/nginx
    dest: /etc/monit/conf.d/nginx
  notify: Reload Service | monit

- name: Trigger All Callbacks
  meta: flush_handlers
