---
- name: nginx | update pidfile preferences
  replace:
    dest: "{{ item }}"
    regexp: '/var/run/\$NAME.pid'
    replace: "{{ nginx_pidfile_path }}"
  with_items:
    - /etc/init.d/nginx
    - /etc/logrotate.d/nginx
  tags:
    - initscript
    - runtime-data
    - pidfile
    - nginx
